# Generated by Django 4.1.6 on 2023-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="live",
            field=models.URLField(null=True),
        ),
    ]
