# Generated by Django 4.1.6 on 2023-02-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_alter_project_github_alter_project_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="live",
            field=models.URLField(blank=True, null=True),
        ),
    ]
