# Generated by Django 4.1.6 on 2023-02-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_project_github_alter_project_live"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(null=True, upload_to="projects"),
        ),
    ]
