# Generated by Django 4.1.6 on 2023-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_resume_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=64)),
                ("lname", models.CharField(max_length=64)),
                ("role", models.CharField(blank=True, max_length=32, null=True)),
                ("company", models.CharField(max_length=64, null=True)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
