# Generated by Django 4.1.6 on 2023-02-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
